spring:
  application:
    name: monitor-service

server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_trace_param
    include-exception: false
---
spring:
  profiles: local
---
spring:
  profiles: docker
  data:
    mongodb:
      host: mongo
---
spring:
  profiles: docker
  redis:
    host: redis