spring:
  application:
    name: proxy-service
---
spring:
  profiles: local, development

server:
  port: 8080

zuul:
  decodeUrl: false
  routes:
    api:
      path: /**
      url: https://api.mercadolibre.com/
#  ratelimit:
#    enabled: true
#    repository: REDIS
#    policy-list:
#      api:
#        - limit: 50000
#          refresh-interval: 10
#          type:
#            - url
#        - limit: 50
#          refresh-interval: 10
#          type:
#            - origin
#        - limit: 10
#          refresh-interval: 60
#          type:
#            - origin
#            - url
---
spring:
  profiles: local

monitor-service:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8081
---
spring:
  profiles: development
  redis:
    host: redis

monitor-service:
  ribbon:
    eureka:
      enabled: false
    listOfServers: monitor-service:8081
