spring:
  application:
    name: proxy-service
---
spring:
  profiles: local, docker

server:
  port: 8080

zuul:
  decodeUrl: false
  routes:
    api:
      path: /**
      url: https://api.mercadolibre.com/
---
spring:
  profiles: local, docker

ratelimit:
  ipinterval: 10
  pathinterval: 10
  ipandpathinterval: 10
  ipmaxrequest: 5
  pathmaxrequest: 5
  ipandpathmaxrequest: 5

---
spring:
  profiles: local

monitor-service:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8081
---
spring:
  profiles: docker
  redis:
    host: redis

monitor-service:
  ribbon:
    eureka:
      enabled: false
    listOfServers: monitor-service:8081
