spring:
  application:
    name: proxy

server:
  port: 8080

zuul:
  routes:
    categories:
      path: /categories/**
      url: https://api.mercadolivre.com/categories/
    currencies:
      path: /currencies/**
      url: https://api.mercadolivre.com/currencies/
    api:
      path: /**
      url: https://api.mercadolibre.com/
  ratelimit:
    enabled: true
    repository: REDIS
    policy-list:
      categories: # rate limit of 5 requests per 60 seconds for the categories endpoint
        - limit: 5
          refresh-interval: 60
          type:
            - origin
      currencies: # rate limit of 1 request per 2 seconds for the currencies endpoint
        - limit: 1
          refresh-interval: 2
          type:
            - origin
